### ISSUE TITLE
Checklist for Page

### ISSUE THREAD

**Issue by Hunta88** [Hunta88/My-Webpage#2]
- [x]  Big title
- [x] Short intro to the page
- [x] directory links to separate pages that will be for Blog Catagories
- [x] 3 Photos of me and the things I do
- [x] Quote somewhere
- [x] Social media Links
- [x] Form for newsletter / to receive email on updates
- [x] Use Iframe somewhere

**Comment by Hunta88** [comment]
All done
